services:
  database:
    build: 
      context: ./database
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - $BACKEND_LOCAL_PORT:$BACKEND_DOCKER_PORT
    depends_on:
      - database
    environment:
      SPRING_APPLICATION_JSON: '{ 
        "spring.datasource.url"  : "jdbc:postgresql://database:5432/$POSTGRES_DB",
        "spring.datasource.username" : "$POSTGRES_USER",
        "spring.datasource.password" : "$POSTGRES_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect"
        }'
    volumes:
      - .m2:/root/.m2

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - $FRONTEND_LOCAL_PORT:$FRONTEND_DOCKER_PORT
    depends_on:
      - backend

volumes:
  postgres_data: