services:
  database:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DATABASE_LOCAL_PORT}:${DATABASE_CONTAINER_PORT}"
    volumes:
      - postgres_db_data:${DATABASE_VOLUME}
    restart: unless-stopped

  backend:
    depends_on: 
      - database
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      FRONTEND_LOCAL_PORT: ${FRONTEND_LOCAL_PORT}
      FRONTEND_IP: ${FRONTEND_IP}
      SPRING_APPLICATION_JSON: 
        '{
          "spring.datasource.url" : "jdbc:postgresql://database:${DATABASE_CONTAINER_PORT}/${POSTGRES_DB}",
          "spring.datasource.username" : "${POSTGRES_USER}",
          "spring.datasource.password" : "${POSTGRES_PASSWORD}",
          "spring.jpa.show-sql" : "true",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
          "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    ports:
      - "${BACKEND_LOCAL_PORT}:${BACKEND_CONTAINER_PORT}"
    volumes:
      - .m2:/root/.m2     
    restart: unless-stopped

  # frontend:
  #   depends_on:
  #     - backend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   environment:
  #     BACKEND_IP: ${BACKEND_IP}
  #     BACKEND_PORT: ${BACKEND_LOCAL_PORT}
  #   ports:
  #     - "${FRONTEND_LOCAL_PORT}:${FRONTEND_CONTAINER_PORT}"
  #   restart: on-failure
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    ports:
      - "${ELASTICSEARCH_LOCAL_PORT}:${ELASTICSEARCH_CONTAINER_PORT}"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: unless-stopped
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    ports:
      - "${KIBANA_LOCAL_PORT}:${KIBANA_CONTAINER_PORT}"
    restart: unless-stopped


volumes:    
  postgres_db_data:
  elasticsearch_data:
    


    
