services:
  database:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DATABASE_LOCAL_PORT}:${DATABASE_DOCKER_PORT}"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    depends_on: 
      - database
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SPRING_APPLICATION_JSON: 
        '{
          "spring.datasource.url" : "jdbc:postgresql://database:${DATABASE_DOCKER_PORT}/${POSTGRES_DB}",
          "spring.datasource.username" : "${POSTGRES_USER}",
          "spring.datasource.password" : "${POSTGRES_PASSWORD}",
          "spring.jpa.show-sql" : "true",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
          "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    ports:
      - "${BACKEND_LOCAL_PORT}:${BACKEND_DOCKER_PORT}"
    volumes:
      - .m2:/root/.m2     # volume for maven dependencies caching, so that we don't have to download them every time we build the image
    restart: on-failure

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:3000"
    restart: on-failure
  
volumes:    
  postgres_db_data:
    


    
